#!/bin/bash

shbookmark_dir="${BASH_SOURCE[0]}";
shbookmark_dir="$( cd -P "$( dirname "$shbookmark_dir" )" && pwd )"

ss=$shbookmark_dir/bookmark.sh

alias ga=".     $ss add    "
alias g=".      $ss go     "
alias gdel=".   $ss delete "
alias gclean=". $ss clean  "
